services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt  # 인증서 볼륨
      - ./certbot/www:/var/www/certbot   # 인증서 발급용 웹루트
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web
    networks:
      - dbre_network
    restart: always

  # Certbot 서비스 추가
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ks3610@gmail.com -d api.desub.kr -d www.api.desub.kr --agree-tos --no-eff-email

  web:
    build: .
    env_file: .env.prod
    volumes:
      - ./dbre_BE:/app/dbre_BE
      - ./staticfiles:/app/staticfiles
    working_dir: /app
    command: poetry run gunicorn --bind 0.0.0.0:8000 dbre_BE.wsgi:application
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/1
      - DJANGO_SETTINGS_MODULE=dbre_BE.settings.prod
      - PYTHONPATH=/app:/app/dbre_BE
      - DJANGO_ENV=prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - dbre_network
    restart: always

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - dbre_network
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dbre_network
    restart: always

  celery_worker:
    build: .
    command: poetry run celery -A dbre_BE worker -l INFO
    volumes:
      - ./dbre_BE:/app/dbre_BE
    environment:
      - DJANGO_SETTINGS_MODULE=dbre_BE.settings.prod
      - PYTHONPATH=/app:/app/dbre_BE
      - REDIS_URL=redis://redis:6379/1
    env_file: .env.prod
    depends_on:
      - redis
      - web
    networks:
      - dbre_network
    restart: always

  celery_beat:
    build: .
    command: poetry run celery -A dbre_BE beat -l INFO
    volumes:
      - ./dbre_BE:/app/dbre_BE
    environment:
      - DJANGO_SETTINGS_MODULE=dbre_BE.settings.prod
      - PYTHONPATH=/app:/app/dbre_BE
      - REDIS_URL=redis://redis:6379/1
    env_file: .env.prod
    depends_on:
      - redis
      - celery_worker
    networks:
      - dbre_network
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - dbre_network

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    networks:
      - dbre_network

volumes:
  postgres_data:

networks:
  dbre_network:
    driver: bridge