services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/nginx/ssl
      - ./staticfiles:/usr/share/nginx/html/staticfiles
    depends_on:
      - web
    restart: always

  web:
    build: .
    env_file: .env.prod
    ports:
      - "8000:8000"
    volumes:
      - ./dbre_BE:/app/dbre_BE
      - ./staticfiles:/app/staticfiles
    working_dir: /app
    command: poetry run gunicorn --bind 0.0.0.0:8000 dbre_BE.wsgi:application
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - DJANGO_SETTINGS_MODULE=dbre_BE.settings.prod
      - PYTHONPATH=/app:/app/dbre_BE
      - DJANGO_ENV=prod
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6666:6379"
    restart: always
    networks:
      - dbre_network


  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:

networks:
  dbre_network:
    driver: bridge
