[tool.poetry]
name = "dbre-project"
version = "0.1.0"
description = ""
authors = ["limsu1015 <tngur1015@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.13"
django = ">=5.1.5,<6.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
